### ISSUE TITLE
Add ability to set database name, user, with environment variables

### ISSUE THREAD

**Issue by aarobc** [bitnami/bitnami-docker-opencart#2]
This would be useful if you're running multiple instances of the container, and want to use only one container for the database. 

In this situation it would be better to have unique a user per container, so there's no concern about tests on one mucking up the database of another.

**Comment by juan131** [comment]
@aarobc currently the Bitnami Docker Images don't support this kind of behaviour. As commented at https://github.com/bitnami/bitnami-docker-joomla/issues/15 the problem is not about being able to use those env var to configure the name ant the user of the database.
The problem is that the first OpenCart will be able to start properly but the second, the third, etc. will consider there is no other OpenCart instance when initialising and they will access the MariaDB server and try to create the database, configure the permissions, etc. causing a conflict.
You can workaround it doing the following:
 - Deploy your first OpenCart.
 - Configure the database setting in the config file.
 - Deploy your second OpenCart (it will create a new database and user with random names). Then configure the database settings in the config file to use the database and the user that the first OpenCart instance created.
 - Finally, connect to the MariaDB container and remove the databases and users created at the second deploy since they won't be used anymore.

**Comment by javsalgar** [comment]
Check this issue, maybe it works for your case as well
https://github.com/bitnami/bitnami-docker-joomla/issues/15#issuecomment-460166889
