### ISSUE TITLE
Error executing 'postInstallation'

### ISSUE THREAD

**Issue by atomicnation** [bitnami/bitnami-docker-opencart#60]
I'm trying to run the bitnami/opencart image against the bitnami/mariadb image. Maria DB container is running. But bitnami/open container exits. Logs are showing:

`Error executing 'postInstallation': PHPNotice: Use of undefined constant DIR_STORAGE - assumed 'DIR_STORAGE' in /opt/bitnami/opencart/system/startup.php on line 70.`

I thought I could temporary solve by editing the file so I runed the image with -it and bash, but now I'm facing 2 issues:
1) Not vim, gedit or nano editors work inside the container. How should I edit the file?
2) How should I define the 'DIR_STORAGE' constant?

**Comment by marcosbc** [comment]
Hi @atomicnation, unfortunately we're unable to reproduce your issue. We executed the `docker-compose.yml` file mentioned in the [README](https://github.com/bitnami/bitnami-docker-opencart#run-the-application-using-docker-compose) and it worked perfectly. How did you deploy OpenCart?

>1. Not vim, gedit or nano editors work inside the container. How should I edit the file?

We just replied a similar question here, which might be to your interest: https://github.com/bitnami/bitnami-docker-mariadb/issues/172#issuecomment-443155518.
If this is just a temporary need, you can enter the container as the `root` user and run the `install_packages vim` command (note that it is a wrapper for `apt-get` in case you want to install any other editor like nano or emacs).

**Comment by atomicnation** [comment]
@marcosbc I found both admin and general config files were empty, so I had to copy some from the opencart github and update them with the necessary configuration for the bitnami-docker-opencart and bitnami-docker-mariadb images. I had to install an editor to the container in order to do so.
Once the config files properly created it worked. But I found it really weird to get these files empty from the official images.

**Comment by marcosbc** [comment]
Hi all, sorry for getting back to you so late.

@avoinea, could you provide more context on how to reproduce that issue? From [this issue](https://github.com/bitnami/bitnami-docker-wordpress/issues/105), it seems that it could be due to a misconfigured container.

@atomicnation We just launched a docker-compose with OpenCart (the one mentioned in the README) and both `config.php` and `admin/config.php` had configuration and were not empty. We also recreated the container (removing the container, maintaining the volume and creating it again), and the configuration was still the same.
Do you have any steps for reproducing that issue? Maybe your container did not initialize properly in the first place.

**Comment by khaines** [comment]
@marcosbc Can you try launching this container via its helm deployment option for kubernetes (as noted in the README)? This container launched fine for me using docker-compose on my dev box, however using the helm chart method results in the error situation the OP had. This was done using the latest docker container.

**Comment by marcosbc** [comment]
@khaines The Helm deployment launches fine for us. Did you do anything apart from launching it, such as logging in, changing the theme, etc., or did it happen right after getting deployed?

If so, are you customizing any of the default parameter values when launching it?

**Comment by hosek** [comment]
I hit this issue with latest image, docker compose is same as example one.

> opencart_1        | opencar INFO  Installing OpenCart...
opencart_1        | Error executing 'postInstallation': PHP Notice:  Use of undefined constant DIR_STORAGE - assumed 'DIR_STORAGE' in /opt/bitnami/opencart/system/startup.php on line 70

**Comment by marcosbc** [comment]
Hi @hosek, unfortunately we're still unable to reproduce your issue. Could you provide more info such as your `docker-compose.yml` file, and check if the `DIR_STORAGE` constant is defined in the following places:

- `/bitnami/opencart/config.php`
- `/bitnami/opencart/admin/config.php`

**Comment by hosek** [comment]
Those files were not present at all. But I found difference between example compose files - in readme it points to **_bitnami/opencart:latest_** and in githubusercontent it points to **_bitnami/opencart:3_** 

Version with **bitnami/opencart:3** is working like charm :)

**Comment by marcosbc** [comment]
Hi @hosek, I'm glad you were able to get it working.

However, I'm a bit confused. The `bitnami/opencart:latest` image points directly to `bitnami/opencart:3` so it should work.

I understand you were using the `docker-compose.yml` file mentioned in [Run the application using Docker Compose](https://github.com/bitnami/bitnami-docker-opencart#run-the-application-using-docker-compose). This image works properly for us, so we're still unsure why you get the error.

Note that the files `/bitnami/opencart/config.php` and `/bitnami/opencart/admin/config.php` are inside the volume `opencart_data`. If you ever see this issue again, it would be great if you could enter the failing image and run the command:

    $ ls -la /bitnami/opencart

Since the initialization fails, you can avoid that by setting `command: tail -f /dev/null` in the compose file, then inside it execute `/app-entrypoint.sh httpd -f /bitnami/apache/conf/httpd.conf` for it to initialize (and fail).

You should see the following files:

**Comment by hosek** [comment]
I'm not using volume, I'm mounting host system folder, but I tried to reproduce the issue - prune system, change opencart from 3 to latest and rerun it.. its working fine now, if I hit the issue again I will check those files. Thanks for the tutorial!
