### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by koernigo** [bitnami/bitnami-docker-opencart#67]
Hi, I just deployed Opencart using Centos 7 and docker 18.09. Also using compose version 1.18.
Everything starting up fine. I have installed this in a cloud instance.
When I open the opencart homepage remotely I get an HTML page without pictures 

Same with the admin page
When I login on the admin page (which uid and pw? I assume bn_opencart pw )
I get an error on localhost. Do I need to run the UI on localhost or is there a way to access it remotely?

Thanks!

Oliver

**Comment by alemorcuq** [comment]
Hi, @koernigo, 

We would need more information in order to reproduce the issue, could you please provide the following information?

- The `docker-compose.yml` file (if you are setting passwords, please replace them with fake ones).
- How you access your homepage.
- How you access the admin page.

Also, the admin account is set using the `OPENCART_USERNAME` and `OPENCART_PASSWORD` environment variables. The default username is `user` and the default password is `bitnami1`. You can find this information in the `README.md` file.

https://github.com/bitnami/bitnami-docker-opencart#environment-variables

**Comment by koernigo** [comment]
Hi Alejandro,

Thanks much for your help!

The docker compose file is the one from the bitnami website.


$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-opencart/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d

After that I am accessing the homepage from a different machine via:  <IP_address>:80
The admin page I reach via: <ip_address>/admin

I tried the uid/pw you sent me and I am still getting a localhost error, even if I don't run this on localhost:

This site can’t be reached

127.0.0.1 refused to connect.

Try:

  *   Checking the connection
  *   Checking the proxy and the firewall<chrome-error://chromewebdata/#buttons>

ERR_CONNECTION_REFUSED


Best

Oliver

________________________________

**Comment by alemorcuq** [comment]
Hi again, Oliver.

It looks like you are using `localhost` as your host and then trying to access it using a different host. Opencart uses the host you specify at setup for every relative URL, that's why images and links point to `localhost` instead of your host. You can change your host with the `OPENCART_HOST` environment variable. Using your `docker-compose.yml`, just replace this line:

`- OPENCART_HOST=localhost`

with this other one:

`- OPENCART_HOST=YOUR_IP_ADDRESS`

Note that this is only effective when Opencart is initialized, that is, at first boot. To test it:

```
$ docker-compose down -v
$ docker-compose up
```

Regards,

Alejandro

**Comment by koernigo** [comment]
Hi Alejandro,

Thanks much, works like a charm now!!

Best

Oliver

________________________________

**Comment by tatsta** [comment]
Hi!
Worked also for me!
Thanks a lot!

KR,
Tatjana

**Comment by alemorcuq** [comment]
I'm glad you were able to solve your issue. Please, let us know any other questions you may have.
